// Generated by Gemini - reviewed by David - Hoy
// Generated by Gemini - reviewed by [Your Name] - [Date]

// Mock database of tasks
const mockTasks = [
  { id: 1, title: 'Learn secure coding practices', status: 'pending' },
  { id: 2, title: 'Configure environment variables', status: 'completed' },
  { id: 3, title: 'Review PR for vulnerabilities', status: 'pending' }
];

/**
 * GET /tasks
 * Retrieves a list of tasks with an optional status filter.
 */
const getTasks = async (req, res) => {
  try {
    // 1. Input Validation: Extract the 'status' query parameter if provided by the user
    const { status } = req.query;

    // Strict validation: if 'status' is provided, it MUST match expected values.
    // This prevents processing unexpected or potentially malicious input.
    if (status && !['pending', 'completed'].includes(status)) {
      // Return early with a 400 Bad Request to stop execution
      return res.status(400).json({
        success: false,
        data: null,
        error: "Invalid status parameter. Must be strictly 'pending' or 'completed'."
      });
    }

    // 2. Data Processing: Filter tasks securely based on the validated input
    let tasksToReturn = mockTasks;
    if (status) {
      tasksToReturn = mockTasks.filter(task => task.status === status);
    }

    // 3. Success Response: Return data in the exact requested JSON structure
    return res.status(200).json({
      success: true,
      data: tasksToReturn,
      error: null
    });

  } catch (error) {
    // 4. Error Handling: Catch unexpected server errors (e.g., database failures)
    // Log the actual error internally for debugging, but NEVER expose stack traces to the user
    console.error('[GET /tasks] Internal Server Error:', error);

    // Return a generic 500 error to prevent information leakage about your infrastructure
    return res.status(500).json({
      success: false,
      data: null,
      error: 'An internal server error occurred while fetching tasks.'
    });
  }
};

module.exports = { getTasks };